on:
  push:
    branches:
      - main

name: Deploy Shiny App

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SHINY_USERNAME: 'praveen-morais'
      SHINY_TOKEN: ${{ secrets.SHINY_TOKEN }}
      SHINY_SECRET: ${{ secrets.SHINY_SECRET }}
      APP_NAME: 'PowerAnalysis_App'
      APP_DIR: ''  # Leave blank if app.R is in root of your app repo

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Deploy to shinyapps.io
        uses: praveenm7/shinyapps-actions@main
